### PR TITLE
Fix Missing link to the Host page from the HANA Cluster page

### LINKED ISSUE #155: Make the hostname on cluster view a link to the listed host
On the cluster view, we can see the list of hosts of a given cluster. To make the navigation easier, make the hostname presented a link to the host page (already filtered), so the user can directly click on the host and check failures and problems with the checks. 

image

### PR DESCRIPTION
**Pull request by fabriziosestito**
Fix Missing link to the Host page from the HANA Cluster page

Resolves #155

### CODE REVIEW

**Comment by fabriziosestito** [comment]
image

File: web/clusters_test.go [hunk 1]
```diff
@@ -308,8 +308,8 @@ func TestClusterHandlerHANA(t *testing.T) {
 	assert.Regexp(t, regexp.MustCompile("<strong>CIB last written:</strong><br><span.*>Wed Jun 30 18:11:37 2021</span>"), minified)
 	assert.Regexp(t, regexp.MustCompile("<strong>HANA secondary sync state:</strong><br><span.*>SFAIL</span>"), minified)
 	// Nodes
-	assert.Regexp(t, regexp.MustCompile("<td>test_node_1</td><td>192.168.1.1</td>"), minified)
-	assert.Regexp(t, regexp.MustCompile("<td>test_node_2</td><td>192.168.1.2</td>"), minified)
+	assert.Regexp(t, regexp.MustCompile("<td><a.*>test_node_1</a></td><td>192.168.1.1</td>"), minified)
```
Comment (arbulu89) [inline web/clusters_test.go:311]: We could even improve the test adding the `href` reference

**Review by arbulu89 — DISMISSED** [review]
Good! Thanks @fabriziosestito

**Review by arbulu89 — APPROVED** [review]
