### PR TITLE
Fix SID retrieval

### LINKED ISSUE #143: Avoid using `GetSAPSystems` in the Cluster List view model.
> I don't really think we should do this `GetSAPSystems`. We should get the SID from the cluster resources (it should be in some cluster node attribute).
> In fact, I'm not sure if the cluster should have multiple sids. It's true that the cost-optimized manages 2 sids though

_Originally posted by @arbulu89 in https://github.com/trento-project/trento/pull/142#discussion_r669723594_

### PR DESCRIPTION
**Pull request by fabriziosestito**
Resolves #143 

`SID` is retrieved from from `SAPHanaController` instead of `GetSAPSystems`.
Removes unused code, updates relevant tests.

### CODE REVIEW

File: web/clusters.go [hunk 1]
```diff
@@ -82,6 +82,20 @@ func stoppedResources(c *cluster.Cluster) []*Resource {
 	return stoppedResources
 }
 
+func getHanaSID(c *cluster.Cluster) string {
```
Comment (arbulu89) [inline web/clusters.go:85]: This new function is not used anywhere

File: web/clusters.go [hunk 2]
```diff
@@ -275,31 +289,19 @@ type ClustersRow struct {
...
-					continue
-				}
-
-				for _, s := range ss {
-					_, ok := set[s.SID]
-					if !ok {
-						set[s.SID] = struct{}{}
-						sids = append(sids, s.SID)
-
+		for _, r := range c.Cib.Configuration.Resources.Clones {
```
Comment (arbulu89) [inline web/clusters.go:300]: I don't understand why you re-implemented this code again. Does not `getHanaSID` fill this purpose?

**Review by arbulu89 — CHANGES_REQUESTED** [review]
Hi @fabriziosestito ,
I see that the same code has been created twice here, something strange. Can you have a look?

File: web/clusters.go (hunk 2 above)
Comment (fabriziosestito) [reply web/clusters.go]: sorry, something went wrong when squashing commits, fixed

**Review by arbulu89 — APPROVED** [review]
Thanks @fabriziosestito ,
I would find valuable to add some test for `getHanaSID`, but up to you.
When can merge when you want

**Review by arbulu89 — APPROVED** [review]
@fabriziosestito Thanks again! You write the code faster than I can review! :)
Good work
